import 'dart:io';

import 'package:code_assets/code_assets.dart';
import 'package:hooks/hooks.dart';
import 'package:logging/logging.dart';
import 'package:native_toolchain_c/native_toolchain_c.dart';

void main(List<String> args) async {
  await build(args, _build);
}

Future<void> _build(BuildInput input, BuildOutputBuilder output) async {
  if (!input.config.buildCodeAssets) return;

  // Guard: ensure vendored source is present.
  final natsHeader = File.fromUri(
    input.packageRoot.resolve('third_party/nats_c/src/nats.h'),
  );
  if (!natsHeader.existsSync()) {
    throw StateError(
      'Vendored nats.c source not found at third_party/nats_c/.\n'
      'The third_party/nats_c/ directory should contain the nats.c source files.',
    );
  }

  final libresslDir = File.fromUri(
    input.packageRoot.resolve('third_party/libressl/sources.txt'),
  );
  if (!libresslDir.existsSync()) {
    throw StateError(
      'Vendored LibreSSL source not found at third_party/libressl/.\n'
      'Run scripts/update_libressl.sh to populate third_party/libressl/.',
    );
  }

  // Load LibreSSL source file list from sources.txt (generated by
  // scripts/update_libressl.sh from CMakeLists.txt).
  final allLibresslSources = libresslDir
      .readAsLinesSync()
      .where((line) => line.trim().isNotEmpty)
      .toList();

  final targetOS = input.config.code.targetOS;
  final targetArch = input.config.code.targetArchitecture;

  // Filter out platform-inappropriate source files.
  // sources.txt contains ALL platform compat files (Windows, AIX, HP-UX, etc.)
  // and all architecture variants — we only compile the ones needed for the
  // target OS and architecture.
  final libresslSources = allLibresslSources
      .where((path) => !_isExcludedSource(path, targetOS, targetArch))
      .toList();

  // Architecture-specific LibreSSL include paths.
  final archIncludes = switch (targetArch) {
    Architecture.arm64 => [
      'third_party/libressl/crypto/arch/aarch64/',
      'third_party/libressl/crypto/bn/arch/aarch64/',
    ],
    Architecture.x64 => [
      'third_party/libressl/crypto/arch/amd64/',
      'third_party/libressl/crypto/bn/arch/amd64/',
    ],
    Architecture.ia32 => ['third_party/libressl/crypto/arch/i386/'],
    _ => <String>[],
  };

  // Single-pass CBuilder: compile all 512 LibreSSL .c files + 43 NATS C .c
  // files together into one shared library. No pkg-config, no dynamic
  // libssl/libcrypto linking.
  final cbuilder = CBuilder.library(
    name: 'nats',
    assetName: 'src/nats_bindings.g.dart',
    std: targetOS == OS.windows ? 'c11' : 'gnu99',
    sources: [...libresslSources, ..._natsSourcesForOS(targetOS)],
    includes: [
      // Hidden namespace wrappers MUST come before include/ so that
      // #include <openssl/ssl.h> finds the wrapper (which uses #include_next
      // to chain to the public header and then imports LSSL_ALIAS/LCRYPTO_ALIAS).
      'third_party/libressl/ssl/hidden/',
      'third_party/libressl/crypto/hidden/',
      // Compat headers (string.h, stdlib.h, etc.) shadow system headers to
      // provide freezero, recallocarray, explicit_bzero, timingsafe_memcmp, etc.
      'third_party/libressl/include/compat/',
      // LibreSSL public headers (openssl/*.h) — found via #include_next from
      // the hidden wrappers above.
      'third_party/libressl/include/',
      // LibreSSL internal crypto headers (crypto_internal.h, etc.)
      'third_party/libressl/crypto/',
      // LibreSSL internal SSL headers
      'third_party/libressl/ssl/',
      // LibreSSL crypto subdirectory includes (cross-module #include "..._local.h").
      // Auto-discovered: all crypto/ subdirs containing .h files, excluding
      // hidden/, compat/, arch/ (handled separately above).
      ..._cryptoSubdirIncludes(input),
      // Architecture-specific headers
      ...archIncludes,
      // NATS C headers
      'third_party/nats_c/src/',
      'third_party/nats_c/src/include/',
    ],
    defines: {
      // --- NATS C defines ---
      '_REENTRANT': null,
      'NATS_HAS_TLS': null,
      'NATS_FORCE_HOST_VERIFICATION': null,

      // --- LibreSSL internal defines ---
      // OpenBSD visibility macros — must be empty on non-OpenBSD.
      '__BEGIN_HIDDEN_DECLS': '',
      '__END_HIDDEN_DECLS': '',
      // Gates internal APIs: CBS_dup, SYSerror, error macros, etc.
      'LIBRESSL_INTERNAL': null,
      // Gates additional crypto-internal APIs.
      'LIBRESSL_CRYPTO_INTERNAL': null,
      // No hardware padlock support.
      'OPENSSL_NO_HW_PADLOCK': null,
      // No assembly — pure C compilation.
      'OPENSSL_NO_ASM': null,
      // Default certificate directory path.
      'OPENSSLDIR': targetOS == OS.windows ? r'"C:\\OpenSSL"' : r'"/etc/ssl"',

      // --- Architecture CPU caps ---
      // Each crypto/arch/<arch>/crypto_cpu_caps.c provides crypto_cpu_caps_init()
      // (and ia32 variants provide crypto_cpu_caps_ia32()). These defines tell
      // crypto_legacy.c to skip its fallback stubs.
      'HAVE_CRYPTO_CPU_CAPS_INIT': null,
      if (targetArch == Architecture.x64 || targetArch == Architecture.ia32)
        'HAVE_CRYPTO_CPU_CAPS_IA32': null,

      // --- Platform HAVE_* feature macros ---
      if (targetOS == OS.macOS || targetOS == OS.linux) ..._posixHaveDefines,
      if (targetOS == OS.macOS) ...{
        // macOS-specific (BSD libc)
        'HAVE_STRLCPY': null,
        'HAVE_STRLCAT': null,
        'HAVE_ARC4RANDOM_BUF': null,
        'HAVE_TIMINGSAFE_BCMP': null,
        'HAVE_GETPROGNAME': null,
        'DARWIN': null,
      },
      if (targetOS == OS.linux) ...{
        // Linux-specific (glibc)
        'HAVE_EXPLICIT_BZERO': null,
        'HAVE_ENDIAN_H': null,
        'LINUX': null,
        '_GNU_SOURCE': null,
      },
      if (targetOS == OS.windows) ...{
        // Vista+ required for CONDITION_VARIABLE used by NATS C win/cond.c.
        '_WIN32_WINNT': '0x0600',
        // Trim rarely-used Windows headers to reduce build time and conflicts.
        'WIN32_LEAN_AND_MEAN': null,
        // Suppress MSVC unsafe-function warnings (sprintf, strcpy, etc.).
        '_CRT_SECURE_NO_WARNINGS': null,
        // MSVC provides strnlen natively.
        'HAVE_STRNLEN': null,
      },
    },
    libraries: [
      if (targetOS == OS.linux) 'pthread',
      if (targetOS == OS.windows) ...const [
        'ws2_32', // Winsock2 — required by NATS C win/sock.c
        'crypt32', // Windows CryptoAPI — required by LibreSSL
        'bcrypt', // Windows BCNG — used by LibreSSL getentropy_win.c
      ],
    ],
  );

  await cbuilder.run(
    input: input,
    output: output,
    logger: Logger('')
      ..level = Level.ALL
      ..onRecord.listen((record) => print(record.message)),
  );
}

// ---------------------------------------------------------------------------
// LibreSSL crypto subdirectory includes
// ---------------------------------------------------------------------------

/// Auto-discovers crypto subdirectories containing headers.
/// Excludes hidden/, compat/, arch/ — these are handled separately in the
/// includes list with specific ordering requirements.
List<String> _cryptoSubdirIncludes(BuildInput input) {
  final cryptoDir = Directory.fromUri(
    input.packageRoot.resolve('third_party/libressl/crypto/'),
  );
  const excludedCryptoDirs = {'hidden', 'compat', 'arch'};
  return cryptoDir
      .listSync()
      .whereType<Directory>()
      .where(
        (d) => !excludedCryptoDirs.contains(
          d.uri.pathSegments[d.uri.pathSegments.length - 2],
        ),
      )
      .where((d) => d.listSync().any((f) => f is File && f.path.endsWith('.h')))
      .map(
        (d) =>
            'third_party/libressl/crypto/${d.uri.pathSegments[d.uri.pathSegments.length - 2]}/',
      )
      .toList()
    ..sort(); // deterministic ordering
}

// ---------------------------------------------------------------------------
// NATS C: 43 source files (32 core + 7 glib + 4 unix)
// Excludes stan/ and win/.
// NOTE: When updating the vendored nats.c source (third_party/nats_c/),
// verify this list against the new source tree. Unlike LibreSSL, this list
// is maintained manually because nats.c has few files and changes rarely.
// ---------------------------------------------------------------------------

/// Returns the NATS C source file list for the given target OS.
/// The 32 core files and 7 glib files are shared across all platforms.
/// The 4 platform-specific threading/socket files differ between Windows
/// (win/) and all other platforms (unix/).
List<String> _natsSourcesForOS(OS targetOS) => [
  // Core (32 files)
  'third_party/nats_c/src/asynccb.c',
  'third_party/nats_c/src/buf.c',
  'third_party/nats_c/src/comsock.c',
  'third_party/nats_c/src/conn.c',
  'third_party/nats_c/src/crypto.c',
  'third_party/nats_c/src/dispatch.c',
  'third_party/nats_c/src/hash.c',
  'third_party/nats_c/src/js.c',
  'third_party/nats_c/src/jsm.c',
  'third_party/nats_c/src/kv.c',
  'third_party/nats_c/src/micro.c',
  'third_party/nats_c/src/micro_client.c',
  'third_party/nats_c/src/micro_endpoint.c',
  'third_party/nats_c/src/micro_error.c',
  'third_party/nats_c/src/micro_monitoring.c',
  'third_party/nats_c/src/micro_request.c',
  'third_party/nats_c/src/msg.c',
  'third_party/nats_c/src/nats.c',
  'third_party/nats_c/src/natstime.c',
  'third_party/nats_c/src/nkeys.c',
  'third_party/nats_c/src/nuid.c',
  'third_party/nats_c/src/object.c',
  'third_party/nats_c/src/opts.c',
  'third_party/nats_c/src/parser.c',
  'third_party/nats_c/src/pub.c',
  'third_party/nats_c/src/srvpool.c',
  'third_party/nats_c/src/stats.c',
  'third_party/nats_c/src/status.c',
  'third_party/nats_c/src/sub.c',
  'third_party/nats_c/src/timer.c',
  'third_party/nats_c/src/url.c',
  'third_party/nats_c/src/util.c',
  // glib (7 files)
  'third_party/nats_c/src/glib/glib.c',
  'third_party/nats_c/src/glib/glib_async_cb.c',
  'third_party/nats_c/src/glib/glib_dispatch_pool.c',
  'third_party/nats_c/src/glib/glib_gc.c',
  'third_party/nats_c/src/glib/glib_last_error.c',
  'third_party/nats_c/src/glib/glib_ssl.c',
  'third_party/nats_c/src/glib/glib_timer.c',
  // Platform-specific threading/sockets (4 files)
  if (targetOS == OS.windows) ...const [
    'third_party/nats_c/src/win/cond.c',
    'third_party/nats_c/src/win/mutex.c',
    'third_party/nats_c/src/win/sock.c',
    'third_party/nats_c/src/win/thread.c',
  ] else ...const [
    'third_party/nats_c/src/unix/cond.c',
    'third_party/nats_c/src/unix/mutex.c',
    'third_party/nats_c/src/unix/sock.c',
    'third_party/nats_c/src/unix/thread.c',
  ],
];

// ---------------------------------------------------------------------------
// Platform-specific source exclusion
// ---------------------------------------------------------------------------
// LibreSSL's sources.txt contains compat files for ALL platforms. Most compat
// files have NO #ifndef HAVE_X guard — they define functions unconditionally.
// Compiling them on a platform that already provides the function causes
// duplicate symbols or compilation failures from missing platform headers.
//
// Files guarded by #ifndef HAVE_X (safe to always include, but unnecessary
// when HAVE_X is defined): bsd-asprintf.c, getdelim.c, getline.c
// ---------------------------------------------------------------------------

/// Returns true if [sourcePath] should be excluded for the given target.
bool _isExcludedSource(
  String sourcePath,
  OS targetOS,
  Architecture? targetArch,
) {
  final basename = sourcePath.split('/').last;

  // Exclude Windows-only files on non-Windows targets (they require
  // windows.h / ws2tcpip.h and won't compile on Unix). On Windows these
  // files are needed and must pass through.
  if (targetOS != OS.windows && _nonWindowsExcludedFiles.contains(basename)) {
    return true;
  }

  // Always exclude getopt_long.c — it redefines struct option from <getopt.h>
  // and conflicts on both macOS and Linux.
  if (basename == 'getopt_long.c') return true;

  // Exclude armcap.c — it references assembly probe functions (_armv7_neon_probe,
  // _armv8_aes_probe, etc.) that only exist in .S files. With OPENSSL_NO_ASM,
  // crypto_legacy.c provides an empty OPENSSL_cpuid_setup() stub instead.
  if (basename == 'armcap.c') return true;

  // Architecture-specific CPU caps: only compile the one for the target arch.
  // Each arch variant defines crypto_cpu_caps_init() (and ia32 variants add
  // crypto_cpu_caps_ia32()); compiling multiple causes duplicate symbols.
  if (sourcePath.contains('/crypto/arch/')) {
    final archDir = _archDirs[targetArch];
    if (archDir == null) return true; // unknown arch — exclude all
    return !sourcePath.contains('/arch/$archDir/');
  }

  // Platform-specific getentropy: exclude all variants except getentropy_win.c.
  // macOS/Linux: system libc provides getentropy (HAVE_GETENTROPY defined).
  // Windows: getentropy_win.c is needed; it passes the _nonWindowsExcludedFiles
  // check on non-Windows and is kept here on Windows.
  if (basename.startsWith('getentropy_') && basename != 'getentropy_win.c') {
    return true;
  }

  // Platform-specific getprogname: only keep the one for the target OS.
  if (basename.startsWith('getprogname_')) {
    return !_getprognameSources.containsKey(targetOS) ||
        basename != _getprognameSources[targetOS];
  }

  // Exclude compat files for functions the target OS already provides.
  // These files have no HAVE_X guard and will cause duplicate symbols.
  final platformExcludes = switch (targetOS) {
    OS.macOS => _macosExcludedCompat,
    OS.linux => _linuxExcludedCompat,
    OS.windows => _windowsExcludedCompat,
    _ => <String>{},
  };
  if (platformExcludes.contains(basename)) return true;

  return false;
}

/// HAVE_* feature macros common to macOS and Linux (both provide these via libc).
const _posixHaveDefines = {
  'HAVE_CLOCK_GETTIME': null,
  'HAVE_GETENTROPY': null,
  'HAVE_ASPRINTF': null,
  'HAVE_MEMMEM': null,
  'HAVE_GETPAGESIZE': null,
  'HAVE_STRCASECMP': null,
  'HAVE_STRNDUP': null,
  'HAVE_STRNLEN': null,
  'HAVE_STRSEP': null,
};

/// Maps Dart Architecture to LibreSSL's crypto/arch/ subdirectory name.
const _archDirs = {
  Architecture.arm64: 'aarch64',
  Architecture.x64: 'amd64',
  Architecture.ia32: 'i386',
};

/// Source files that are Windows-only (require windows.h / ws2tcpip.h)
/// and must be excluded when building for non-Windows targets.
const _nonWindowsExcludedFiles = {
  'b_win.c',
  'ui_openssl_win.c',
  'crypto_lock_win.c',
  'explicit_bzero_win.c',
  'getentropy_win.c',
  'getprogname_windows.c',
  'posix_win.c',
};

/// Platform-specific getprogname implementations.
const _getprognameSources = {
  OS.linux: 'getprogname_linux.c',
  OS.windows: 'getprogname_windows.c',
};

/// Compat files excluded on macOS because macOS provides these functions
/// natively (HAVE_X is defined) and the files have no guard.
const _macosExcludedCompat = {
  'arc4random.c', // HAVE_ARC4RANDOM_BUF
  'arc4random_uniform.c', // part of arc4random family
  'getpagesize.c', // HAVE_GETPAGESIZE
  'strcasecmp.c', // HAVE_STRCASECMP
  'strlcat.c', // HAVE_STRLCAT
  'strlcpy.c', // HAVE_STRLCPY
  'strndup.c', // HAVE_STRNDUP
  'strnlen.c', // HAVE_STRNLEN
  'strsep.c', // HAVE_STRSEP
  'timingsafe_bcmp.c', // HAVE_TIMINGSAFE_BCMP
};

/// Compat files excluded on Linux because Linux (glibc) provides these
/// functions natively (HAVE_X is defined) and the files have no guard.
const _linuxExcludedCompat = {
  'explicit_bzero.c', // HAVE_EXPLICIT_BZERO
  'getpagesize.c', // HAVE_GETPAGESIZE
  'strcasecmp.c', // HAVE_STRCASECMP
  'strndup.c', // HAVE_STRNDUP
  'strnlen.c', // HAVE_STRNLEN
  'strsep.c', // HAVE_STRSEP
};

/// Compat files excluded on Windows because MSVC/Win32 provides them natively.
/// Do NOT add explicit_bzero_win.c, getentropy_win.c, getprogname_windows.c,
/// or posix_win.c — Windows needs those compat implementations.
const _windowsExcludedCompat = {
  'strcasecmp.c', // n-win.h defines strcasecmp as _stricmp
  'getpagesize.c', // Windows: GetSystemInfo() provides page size
  'strndup.c', // available in MSVC 14+
  'strnlen.c', // available in MSVC (HAVE_STRNLEN defined)
  'timingsafe_bcmp.c', // not needed on Windows
};
